- id: front_door_open
  alias: Front Door Open
  initial_state: False
  hide_entity: False
  trigger:
    platform: state
    entity_id: device_tracker.jardi_phone, device_tracker.juni_phone
    from: 'not_home'
    to: 'home'
  action:
    - wait_template: "{{ states('binary_sensor.front_door') == 'on' }}"
      timeout: 00:05:00
#    - delay: 00:00:01
    - service: media_player.turn_on
      entity_id: media_player.living_room_speaker
    - service: media_player.volume_set
      entity_id: media_player.living_room_speaker
      data:
        volume_level: 0.5
    - service: media_player.play_media
      entity_id: media_player.living_room_speaker
      data:
        media_content_id: http://91.221.151.155/listen.mp3
        media_content_type: 'audio/mp4'
#    - service: tts.google_say
#      entity_id: media_player.living_room_speaker
#      data_template:
#        message: >
#          Welcome home
#          {{ trigger.to_state.attributes.friendly_name }}!


- alias: 'Open Front Door - Turn on Light'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.front_porch
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.front_porch
    - delay: '00:02:00'
    - service: homeassistant.turn_off
      entity_id: switch.front_porch

- alias: 'Arriving Home - Turn on Light'
  trigger:
    - platform: state
      entity_id: group.presence_detection
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.front_porch
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.front_porch
    - delay: '00:10:00'
    - service: homeassistant.turn_off
      entity_id: switch.front_porch
